#!/usr/bin/python
# BEFORE USING THIS SCRIPT.
# mkdir ~/timelapse 
# this file should live in ~/timelapse and is run with command "python ~/timelapse/timelapse.py

import time
from picamera import PiCamera
from os import system

camera = PiCamera()
camera.resolution = (1920, 1080)
# my camera was flipped and upside down - this fixes that
camera.vflip = True
camera.hflip = True

SleepTimeL = 1
FrameCount = 0
FrameStop = 240

WAIT = int(FrameStop)*int(SleepTimeL)/60

print('Photography will take approximately ' + str(WAIT) + ' minutes')
print('Taking photos now')
while (FrameCount < FrameStop):
    print('Picture:' + str(FrameCount) + ' of ' + str(FrameStop))
    camera.capture('image' + str(FrameCount).zfill(4) + '.jpg')
    time.sleep(SleepTimeL);
    FrameCount = FrameCount + 1
