configName: Artemis_PDU
folderName: Artemis_PDU
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: ATSAME51N19A
projectName: Artemis_PDU
settings:
  PackageFilter: bootloader;bootloader_apps_sdcard;bsp;classb_sam_e5x_d5x;core;core_apps_sam_d5x_e5x;crypto;csp;csp_apps_sam_d5x_e5x;dev_packs;gfx;gfx_apps_sam_d5x_e5x;net;net_apps_sam_e5x;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.5.104\atdf\ATSAME51N19A.atdf
